In [123]:
import torch

In [124]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reshape and View

In [125]:
# Reshape and View
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### **Reshape if the number of items is not known using -1\**

In [126]:
# Reshape if the number of items is not known using -1
my_torch2 = torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [128]:
my_torch2 = torch.arange(15)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [129]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

### opposite direction

In [130]:
# opposite direction
my_torch2 = torch.arange(15)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [131]:
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [132]:
my_torch2 = torch.arange(15)
print(my_torch2)
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

### **View**

In [133]:
# View
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

#### Differences bewwen Shape and View:
[SO discussion](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)

### With reshape and view, they will update

In [135]:
# With reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [137]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [138]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

## Slices

In [139]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Grab a specific item

In [140]:
# Grab a specific item
my_torch7[7]

tensor(7)

Grab a slice

In [141]:
# Grab a slice
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [142]:
# Get the second column
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [143]:
# Return a column
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])