# TENSOR MATH OPERATIONS

- Add, Substract, Multiply, Divide, Remainders, Exponents
- Shorthand and Longhand expressions
- Reassingnment

In [86]:
import torch
import numpy as np

In [87]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [88]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [89]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [90]:
# Another way to add Longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [91]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [92]:
# Substraction Longhand
torch.sub(tensor_b, tensor_a)


tensor([4, 4, 4, 4])

In [93]:
# Alias to sub
torch.subtract(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [94]:
# Multplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [95]:
# Multplication Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [96]:
# Multiplication Longhand
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [97]:
# Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [98]:
# Division Longhand
torch.divide(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [99]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [100]:
# Remainder (Modulus)
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [101]:
# Remainder (Modulus) Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [102]:
# Exponent / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [103]:
# Exponent / power Longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [104]:
# Reassignment
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a = tensor_a +  tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [105]:
# Reassignment with method add_
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])